version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "brownag"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    pull-request-branch-name:
      separator: "/"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "brownag"
    commit-message:
      prefix: "ci(deps):"
    groups:
      actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    pull-request-branch-name:
      separator: "/"
